default: &default
  adapter: postgresql
  pool: 5
  encoding: unicode
  timeout: 5000


development:
  <<: *default
  database: hilltop-kennels_development


test:
  <<: *default
  database: hilltop-kennels_test


production:
  <<: *default
  database: hilltop-kennels_production